// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAPvP7nMWwAyaJCcQwWkFspz_0K-pmd9I',
    appId: '1:145722104658:web:27b88ca0ff36193af6f88b',
    messagingSenderId: '145722104658',
    projectId: 'foodie-bc5b8',
    authDomain: 'foodie-bc5b8.firebaseapp.com',
    storageBucket: 'foodie-bc5b8.appspot.com',
    measurementId: 'G-YV5YWCG631',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU2oaFVlwN8Iv7D8ymh4GQkwerMN-rfck',
    appId: '1:145722104658:android:d10aa64a394ff399f6f88b',
    messagingSenderId: '145722104658',
    projectId: 'foodie-bc5b8',
    storageBucket: 'foodie-bc5b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6GltLJ8lUGdnjxrrr9zMgAEIyY5KI70U',
    appId: '1:145722104658:ios:59b0b6d5ae7aa815f6f88b',
    messagingSenderId: '145722104658',
    projectId: 'foodie-bc5b8',
    storageBucket: 'foodie-bc5b8.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6GltLJ8lUGdnjxrrr9zMgAEIyY5KI70U',
    appId: '1:145722104658:ios:74726449d3664939f6f88b',
    messagingSenderId: '145722104658',
    projectId: 'foodie-bc5b8',
    storageBucket: 'foodie-bc5b8.appspot.com',
    iosBundleId: 'com.example.foodDelivery.RunnerTests',
  );
}
